# Generated by Django 4.1.7 on 2023-03-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_menuitem_menu_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, help_text='Имя для вызова через template tag', max_length=250, null=True, verbose_name='Имя для template tag'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, help_text='url name в модуле urls.py', max_length=250, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu_app.menuitem', verbose_name='Дочерний элемент'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='url name в модуле urls.py', max_length=250, verbose_name='Ссылка'),
        ),
    ]
